In [70]:
import numpy as np

In [71]:
import pandas as pd

In [72]:
import os

In [73]:
os.getcwd()

'c:\\Users\\rampe\\Desktop\\ML_algo\\ML_algo\\Code'

In [74]:
df=pd.read_csv('c:\\Users\\rampe\\Desktop\\ML_algo\\ML_algo\\DataBase\\diabetes.csv')

In [75]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [76]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [77]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [79]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [80]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [81]:
X.shape,y.shape

((768, 8), (768,))

In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=25, test_size=0.25)

In [83]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((576, 8), (192, 8), (576,), (192,))

In [84]:
import pickle
from sklearn.preprocessing import StandardScaler
def standard_scaler(X_train,X_test):
    scaler=StandardScaler()
    X_train_scaler=scaler.fit_transform(X_train)
    X_test_scaler=scaler.transform(X_test)

    file=open('C:\\Users\\rampe\\Desktop\\ML_algo\\ML_algo\\Model\\standardscaler.pkl','wb')
    pickle.dump(scaler,file)
    file.close()

    return X_train_scaler,X_test_scaler


In [85]:
X_train_scaler,X_test_scaler=standard_scaler(X_train,X_test)

In [86]:
X_train_scaler

array([[-0.82827947,  1.83444042, -0.31525359, ...,  0.2723758 ,
        -0.42508999,  0.37784439],
       [ 1.24216246, -1.15450289,  0.22198329, ...,  0.82517072,
        -0.0415753 ,  0.46339407],
       [ 0.05905278, -0.81555056,  0.00708854, ...,  0.00914013,
         0.41923693, -0.81985104],
       ...,
       [ 0.05905278, -0.23008744, -0.31525359, ..., -0.41203695,
        -1.02563238, -0.81985104],
       [-0.23672464, -0.19927359, -0.20780621, ...,  0.79884715,
        -0.95428081, -0.47765234],
       [-0.23672464,  1.49548809, -0.31525359, ...,  0.32502294,
        -0.34184649, -0.306553  ]])

In [87]:
from sklearn.linear_model import LogisticRegression
clf= LogisticRegression()
clf.fit(X_train_scaler, y_train)

LogisticRegression()

In [88]:
from sklearn.model_selection import GridSearchCV
parameters = [{'penalty': ['l1', 'l2', 'elasticnet'], 'C':[0.25, 0.5, 0.75, 1], 'random_state': [0, 42, 50, 69, 129], 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}]
grid_search = GridSearchCV(estimator=clf, 
                           param_grid=parameters, 
                           scoring='accuracy', 
                           cv=10, 
                           n_jobs=-1)
grid_search.fit(X_train_scaler, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.3f}%".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Best Accuracy: 76.742%
Best Parameters: {'C': 0.25, 'penalty': 'l1', 'random_state': 0, 'solver': 'liblinear'}


c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
1600 fits failed out of a total of 3000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
200 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn

In [89]:
y_pred = clf.predict(X_test_scaler)

In [90]:
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1])

In [91]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accu = accuracy_score(y_test, y_pred)
print("Test set Accuracy: {:.3f}%".format(accu*100))

[[112  18]
 [ 24  38]]
Test set Accuracy: 78.125%


In [92]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=clf, cv=10, X=X_train, y=y_train)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 75.87 %
Standard deviation: 4.10 %


c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#l

In [93]:
from sklearn.linear_model import LogisticRegression
clf_2 = LogisticRegression(random_state=0, C=0.25, penalty='l1', solver='saga')
clf_2.fit(X_train_scaler, y_train)

LogisticRegression(C=0.25, penalty='l1', random_state=0, solver='saga')

In [94]:
y_pred_2 = clf_2.predict(X_test)
print(y_pred_2)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1]


c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [95]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=clf_2, cv=10, X=X_train, y=y_train)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard deviation: {:.2f} %".format(accuracies.std()*100))

c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Accuracy: 68.24 %
Standard deviation: 4.15 %


c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\rampe\Desktop\ML_algo\ML_algo\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\rampe\Desktop\ML_algo\ML_algo\L

In [96]:
import pickle
file=open('C:\\Users\\rampe\\Desktop\\ML_algo\\ML_algo\\Model\\modelforprediction.pkl','wb')
pickle.dump(clf,file)
file.close()